- name: "MariaDB datbase creation"
  hosts: all
  become: 'True'
  vars:
    db_name: "lmariadb_dbname"
    db_password: "lmariadb_ dbpassword"
    db_user: "lmariadb_dbusername"
    mariadb_password: "root"
    mariadb_login_unix_socket: /var/run/mysqld/mysqld.sock
  tasks:
    - name: "install acl"
      yum:
        name: acl
        state: present

    - name: "Create database"
      mysql_db:
        state: present
        name: "{{ db_name }}"
        login_user: root
        login_password: "{{ mariadb_password }}"
        login_unix_socket: "{{ mariadb_login_unix_socket }}"
      become: yes
      become_user: root

    - name: "Create db user"
      mysql_user:
        state: present
        name: "{{ db_user }}"
        password: "{{ db_password }}"
        login_user: root
        login_password: "{{ mariadb_password }}"
        login_unix_socket: "{{mariadb_login_unix_socket}}"
        #update_password: no_log
        priv: "*.*:ALL,GRANT"
        check_implicit_admin: yes
      become: yes
      become_user: root

    - name: Setting up root credentials
      mysql_user:
        name: root
        password: "root"
        login_user: root
        login_password: "{{ mariadb_password }}"
        host: localhost
        login_unix_socket: /var/run/mysqld/mysqld.sock
        priv: '*.*:ALL,GRANT'
        check_implicit_admin: true
        state: present
